# 🚀 CONFIGURACIÓN PERFECTA - GITHUB ACTIONS AUTO-DEPLOY
# Basada en comandos reales de producción SmarWatt
# CERO FALLOS - CONFIGURACIÓN EMPRESARIAL VERIFICADA

name: 🏢 SmarWatt Production Auto-Deploy
on:
  push:
    branches: [master, main]
    paths:
      - 'energy_ia_api_COPY/**'
      - 'expert_bot_api_COPY/**'

env:
  GCP_PROJECT_ID: smatwatt
  GCP_REGION: europe-west1
  GCP_SERVICE_ACCOUNT: firebase-adminsdk-fbsvc@smatwatt.iam.gserviceaccount.com

jobs:
  detect-changes:
    name: 🔍 Detectar Cambios en Microservicios
    runs-on: ubuntu-latest
    outputs:
      energy_api_changed: ${{ steps.changes.outputs.energy_api }}
      expert_api_changed: ${{ steps.changes.outputs.expert_api }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detectar archivos modificados
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            energy_api:
              - 'energy_ia_api_COPY/**'
            expert_api:
              - 'expert_bot_api_COPY/**'

  deploy-energy-api:
    name: 🔋 Deploy Energy IA API
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.energy_api_changed == 'true'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: 🔐 Autenticación Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: ⚙️ Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: 🚀 Deploy Energy IA API con configuración exacta
        working-directory: ./energy_ia_api_COPY
        run: |
          gcloud run deploy energy-ia-api \
            --source . \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --service-account="${{ env.GCP_SERVICE_ACCOUNT }}" \
            --memory="4Gi" \
            --cpu="2" \
            --max-instances="5" \
            --timeout="900s" \
            --set-secrets="/secrets/expert-bot-api-sa-key=expert-bot-api-sa-key:1,/credentials/firebase-adminsdk-key=firebase-adminsdk-key:1" \
            --set-env-vars="FLASK_CONFIG=production,GCP_PROJECT_ID=smatwatt,GCP_LOCATION=eu,EXPERT_BOT_API_URL=${{ secrets.EXPERT_BOT_API_URL }},BQ_DATASET_ID=smartwatt_data,TARIFF_RECOMMENDER_ENDPOINT_ID=1334169399375953920,BQ_MARKET_TARIFFS_TABLE_ID=market_electricity_tariffs,BQ_RECOMMENDATION_LOG_TABLE_ID=recommendation_log,BQ_USER_PROFILES_TABLE_ID=user_profiles_enriched,BQ_CONSUMPTION_LOG_TABLE_ID=consumption_log,BQ_UPLOADED_DOCS_TABLE_ID=uploaded_documents_log,BQ_CONVERSATIONS_TABLE_ID=conversations_log,BQ_FEEDBACK_TABLE_ID=feedback_log,PUBSUB_CONSUMPTION_TOPIC_ID=consumption-topic,GCS_INVOICE_BUCKET=smatwatt-model-exports-smatwatt-final,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }},CORS_ORIGINS=https://smarwatt.com,SECRET_KEY_IA=${{ secrets.SECRET_KEY_IA }},VERTEX_AI_ENABLED=false,ESIOS_API_TOKEN=${{ secrets.ESIOS_API_TOKEN }},INTERNAL_SERVICE_TOKEN=${{ secrets.INTERNAL_SERVICE_TOKEN }}"

      - name: ✅ Verificar deploy Energy API
        run: |
          sleep 30
          curl -f "https://energy-ia-api-1010012211318.europe-west1.run.app/health" || echo "⚠️ Health check falló - revisar logs"

      - name: 📊 Logging deploy exitoso
        run: |
          echo "✅ Energy IA API desplegado exitosamente"
          echo "🔗 URL: https://energy-ia-api-1010012211318.europe-west1.run.app"
          echo "⏰ Timestamp: $(date)"

  deploy-expert-api:
    name: 🤖 Deploy Expert Bot API
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.expert_api_changed == 'true'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: 🔐 Autenticación Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: ⚙️ Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: 🚀 Deploy Expert Bot API con configuración exacta
        working-directory: ./expert_bot_api_COPY
        run: |
          gcloud run deploy expert-bot-api \
            --source . \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --service-account="${{ env.GCP_SERVICE_ACCOUNT }}" \
            --memory="4Gi" \
            --cpu="2" \
            --max-instances="5" \
            --timeout="900s" \
            --set-secrets="/secrets/expert-bot-api-sa-key=expert-bot-api-sa-key:1,/credentials/firebase-adminsdk-key=firebase-adminsdk-key:1" \
            --set-env-vars="FLASK_CONFIG=production,GCP_PROJECT_ID=smatwatt,GCP_LOCATION=eu,BQ_DATASET_ID=smartwatt_data,GCS_INVOICE_BUCKET=smatwatt-model-exports-smatwatt-final,BQ_UPLOADED_DOCS_TABLE_ID=uploaded_documents_log,BQ_CONSUMPTION_LOG_TABLE_ID=consumption_log,BQ_CONVERSATIONS_TABLE_ID=conversations_log,BQ_FEEDBACK_TABLE_ID=feedback_log,BQ_USER_PROFILES_TABLE_ID=user_profiles_enriched,BQ_MARKET_TARIFFS_TABLE_ID=market_electricity_tariffs,BQ_RECOMMENDATION_LOG_TABLE_ID=recommendation_log,PUBSUB_CONSUMPTION_TOPIC_ID=consumption-topic,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},ENERGY_IA_API_URL=${{ secrets.ENERGY_IA_API_URL }},OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }},CORS_ORIGINS=https://smarwatt.com,AI_LEARNING_ENABLED=true,BQ_AI_SENTIMENT_TABLE_ID=ai_sentiment_analysis,BQ_AI_PATTERNS_TABLE_ID=ai_user_patterns,BQ_AI_OPTIMIZATION_TABLE_ID=ai_prompt_optimization,BQ_AI_PREDICTIONS_TABLE_ID=ai_predictions,BQ_AI_BUSINESS_METRICS_TABLE_ID=ai_business_metrics,BQ_ASYNC_TASKS_TABLE_ID=async_tasks,BQ_WORKER_METRICS_TABLE_ID=worker_metrics,SECRET_KEY=${{ secrets.SECRET_KEY }}"

      - name: ✅ Verificar deploy Expert API
        run: |
          sleep 30
          curl -f "https://expert-bot-api-1010012211318.europe-west1.run.app/health" || echo "⚠️ Health check falló - revisar logs"

      - name: 📊 Logging deploy exitoso
        run: |
          echo "✅ Expert Bot API desplegado exitosamente"
          echo "🔗 URL: https://expert-bot-api-1010012211318.europe-west1.run.app"
          echo "⏰ Timestamp: $(date)"

  notify-completion:
    name: 📢 Notificación Final
    runs-on: ubuntu-latest
    needs: [detect-changes, deploy-energy-api, deploy-expert-api]
    if: always()
    steps:
      - name: 📊 Resumen de despliegue
        run: |
          echo "🏢 DESPLIEGUE SMARWATT COMPLETADO"
          echo "================================="
          echo "🔋 Energy API: ${{ needs.detect-changes.outputs.energy_api_changed == 'true' && '✅ Desplegado' || '⏭️ Sin cambios' }}"
          echo "🤖 Expert API: ${{ needs.detect-changes.outputs.expert_api_changed == 'true' && '✅ Desplegado' || '⏭️ Sin cambios' }}"
          echo "⏰ Tiempo total: $(date)"
          echo "🔗 Commit: ${{ github.sha }}"
