# .github/workflows/deploy-expert-bot-api.yml
name: 'Deploy Expert Bot API'

on:
  push:
    branches: [master]
    paths:
      - 'expert_bot_api_COPY/**'
      - '.github/workflows/deploy-expert-bot-api.yml'

jobs:
  deploy:
    name: 'Deploy to Cloud Run'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      SERVICE_NAME: expert-bot-api
      GCP_REGION: europe-west1
      GCP_PROJECT: smatwatt
      GCP_SA: "firebase-adminsdk-fbsvc@smatwatt.iam.gserviceaccount.com"
      SOURCE_PATH: ./expert_bot_api_COPY

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: 'Build and Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \\
            --source ${{ env.SOURCE_PATH }} \\
            --platform managed \\
            --region ${{ env.GCP_REGION }} \\
            --allow-unauthenticated \\
            --service-account="${{ env.GCP_SA }}" \\
            --memory="4Gi" \\
            --cpu="2" \\
            --max-instances="5" \\
            --timeout="900s" \\
            --set-secrets="${{ secrets.GCLOUD_RUN_SECRETS }}" \\
            --set-env-vars="^##^FLASK_CONFIG=production##GCP_PROJECT_ID=${{ env.GCP_PROJECT }}##GCP_LOCATION=eu##BQ_DATASET_ID=smartwatt_data##GCS_INVOICE_BUCKET=smatwatt-model-exports-smatwatt-final##BQ_UPLOADED_DOCS_TABLE_ID=uploaded_documents_log##BQ_CONSUMPTION_LOG_TABLE_ID=consumption_log##BQ_CONVERSATIONS_TABLE_ID=conversations_log##BQ_FEEDBACK_TABLE_ID=feedback_log##BQ_USER_PROFILES_TABLE_ID=user_profiles_enriched##BQ_MARKET_TARIFFS_TABLE_ID=market_electricity_tariffs##BQ_RECOMMENDATION_LOG_TABLE_ID=recommendation_log##PUBSUB_CONSUMPTION_TOPIC_ID=consumption-topic##GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}##ENERGY_IA_API_URL=${{ secrets.ENERGY_IA_API_URL }}##OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}##CORS_ORIGINS=https://smarwatt.com##AI_LEARNING_ENABLED=true##BQ_AI_SENTIMENT_TABLE_ID=ai_sentiment_analysis##BQ_AI_PATTERNS_TABLE_ID=ai_user_patterns##BQ_AI_OPTIMIZATION_TABLE_ID=ai_prompt_optimization##BQ_AI_PREDICTIONS_TABLE_ID=ai_predictions##BQ_AI_BUSINESS_METRICS_TABLE_ID=ai_business_metrics##BQ_ASYNC_TASKS_TABLE_ID=async_tasks##BQ_WORKER_METRICS_TABLE_ID=worker_metrics##SECRET_KEY=${{ secrets.SECRET_KEY }}"
